SUPABASE_URL=https://sgopozjsvoqlpmjvfrgc.supabase.co
SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNnb3Bvempzdm9xbHBtanZmcmdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNjUyMDIsImV4cCI6MjA2ODk0MTIwMn0.CoY60Bq9BPdf1frhn4_foYxY6xrPdl5TErEGV0jx4KE

GOOGLE_CLIENT_ID=447038806959-6sqppclts31tbm8kja06fteogul4agcm.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET=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

ENCRYPTION_SECRET_KEY=kHjszzL0ssfdD4TW5QnREdqqTWYcVhhjny9eXzCw42A=
